### ISSUE TITLE
Add PTVS scheduled CI run to coincide with pylance releases

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/PTVS#7601]
Modify the PTVS yaml to perform a scheduled run every week, sometime after the pylance release, so it gets bundled up properly and in a timely manner.
Pylance releases happen on wednesdays, but the VS insertion takes a while to run checks, so schedule the PTVS build Thursday evening so we can hopefully merge it in to VS on Fridays.

The compliance pipeline runs nightly, so you can use this schedule as a sample and modify it:

```yaml
# Trigger builds on a nightly schedule, as long as there are changes
# All times are in UTC, so 8AM = Midnight PST
schedules:
- cron: "0 8 * * *"
  displayName: Nightly build
  branches:
    include:
    - main
```

See https://learn.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml for cron reference
